import { useState, useEffect, useRef, useMemo } from "react";
import {
  Send, Paperclip, Smile, MoreVertical, Phone,
  Video, Sparkles, LayoutTemplate, Loader2, MessageSquare,
  ShieldCheck, ChevronLeft, X, FileImage, FileText, Mic
} from "lucide-react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Avatar, AvatarFallback } from "./ui/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const ATTACHMENT_ACCEPT = {
  document: ".pdf,.doc,.docx,.xls,.xlsx,.txt,.csv",
  image: "image/*",
  audio: "audio/*",
} as const;

interface ChatInterfaceProps {
  activeContact: string | null;
  onOpenTemplates: () => void;
  onBack?: () => void;
  onCloseChat?: () => void;
  templateBody?: string;
  onTemplateConsumed?: () => void;
}

export function ChatInterface({
  activeContact,
  onOpenTemplates,
  onBack,
  onCloseChat,
  templateBody,
  onTemplateConsumed
}: ChatInterfaceProps) {
  const handleClose = onCloseChat ?? onBack;
  const [message, setMessage] = useState("");
  const [attachment, setAttachment] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [fileAccept, setFileAccept] = useState<string>(ATTACHMENT_ACCEPT.document);
  const scrollRef = useRef<HTMLDivElement>(null);
  const queryClient = useQueryClient();

  // --- 1. IDENTITY LOOKUP (Show Name instead of Number) ---
  const { data: contacts = [] } = useQuery({
    queryKey: ["contacts"],
    queryFn: api.contacts.getAll,
  });

  const contactDetails = useMemo(() => {
    return contacts.find(c => c.phone === activeContact);
  }, [contacts, activeContact]);

  const displayName = contactDetails?.name || activeContact;

  // --- 2. SYNC TEMPLATE BUFFER ---
  useEffect(() => {
    if (templateBody) {
      setMessage(templateBody);
      if (onTemplateConsumed) onTemplateConsumed();
      toast.success("Template added to message");
    }
  }, [templateBody, onTemplateConsumed]);

  // --- 3. FETCH MESSAGES ---
  const { data: messages = [], isLoading } = useQuery({
    queryKey: ["messages", activeContact],
    queryFn: () => api.chat.getMessages(activeContact!),
    enabled: !!activeContact,
    refetchInterval: 3000,
  });

  // --- 4. AI ASSIST MUTATION (The "Magic" Button) ---
  // Inside ChatInterface.tsx
  const aiAssistMutation = useMutation({
    mutationFn: async () => {
      const lastIncoming = [...messages].reverse().find(m => !m.is_from_me);
      const prompt = lastIncoming
        ? `Draft a professional WhatsApp reply to this: "${lastIncoming.content}"`
        : "Suggest a friendly greeting to re-engage a property lead.";

      return api.helpbot.assist(prompt); // <--- Using the new assist method
    },
    onSuccess: (data: { output?: string }) => {
      setMessage(typeof data?.output === "string" ? data.output : "");
      toast.success("Response generated by Forge");
    },
  });

  // --- 5. SEND MESSAGE MUTATION ---
  const sendMessageMutation = useMutation({
    mutationFn: ({ to, msg }: { to: string; msg: string }) => api.chat.sendMessage(to, msg),
    onSuccess: () => {
      setMessage("");
      setAttachment(null);
      queryClient.invalidateQueries({ queryKey: ["messages", activeContact] });
    },
    onError: () => toast.error("WhatsApp Link Offline. Check WAHA connection."),
  });

  const sendMediaMutation = useMutation({
    mutationFn: async ({ to, caption, file }: { to: string; caption: string; file: File }) => {
      const res = await api.chat.sendMedia(to, caption, file);
      return res as { status?: string; message?: { content: string; is_from_me: boolean; time: string } };
    },
    onSuccess: (data, variables) => {
      setMessage("");
      setAttachment(null);
      if (fileInputRef.current) fileInputRef.current.value = "";
      const msg = data?.message;
      const contact = variables.to;
      if (msg && contact) {
        queryClient.setQueryData<{ content: string; is_from_me: boolean; time: string }[]>(
          ["messages", contact],
          (old) => (old ? [...old, msg] : [msg])
        );
      }
      // Refetch after a short delay so server state is in sync and message stays in history
      setTimeout(() => {
        queryClient.invalidateQueries({ queryKey: ["messages", contact] });
      }, 400);
      toast.success("Attachment sent");
    },
    onError: (e: Error) => toast.error(e.message || "Failed to send attachment"),
  });

  // --- AUTO SCROLL ---
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const formatLocalTime = (isoString: string) => {
    if (!isoString) return "--:--";
    try {
      const date = new Date(isoString);
      return date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true });
    } catch (e) { return "00:00"; }
  };

  const getDayKey = (isoString: string) => {
    if (!isoString) return "unknown";
    const d = new Date(isoString);
    if (Number.isNaN(d.getTime())) return "unknown";
    // Local day key (WhatsApp-style separators should follow local time)
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  };

  const formatDayLabel = (isoString: string) => {
    if (!isoString) return "";
    const d = new Date(isoString);
    if (Number.isNaN(d.getTime())) return "";
    const now = new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
    const startOfThatDay = new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
    const diffDays = Math.round((startOfToday - startOfThatDay) / (24 * 60 * 60 * 1000));
    if (diffDays === 0) return "Today";
    if (diffDays === 1) return "Yesterday";
    return d.toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric", year: "numeric" });
  };

  const interpolateMessage = (msg: string, contactPhone: string): string => {
    let interpolated = msg;
    const contact = contacts.find(c => c.phone === contactPhone);
    if (contact) {
      interpolated = interpolated.replace(/\{\{name\}\}/g, contact.name || contactPhone);
    }
    return interpolated;
  };

  const handleSend = () => {
    if (!activeContact) return;
    const isPending = sendMessageMutation.isPending || sendMediaMutation.isPending;
    const interpolatedMessage = interpolateMessage(message, activeContact);

    if (attachment) {
      if (isPending) return;
      sendMediaMutation.mutate({ to: activeContact, caption: interpolatedMessage, file: attachment });
      return;
    }
    if (!message.trim() || isPending) return;
    sendMessageMutation.mutate({ to: activeContact, msg: interpolatedMessage });
  };

  const canSend = message.trim() || attachment;
  const isSending = sendMessageMutation.isPending || sendMediaMutation.isPending;

  if (!activeContact) {
    return (
      <div className="flex-1 w-full h-full flex flex-col items-center justify-center bg-background relative overflow-hidden transition-colors duration-500">
        <div className="absolute inset-0 opacity-[0.03] dark:opacity-10"
          style={{ backgroundImage: `linear-gradient(hsl(var(--foreground)) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--foreground)) 1px, transparent 1px)`, backgroundSize: '40px 40px' }}
        />
        <div className="relative z-10 flex flex-col items-center w-full max-w-2xl px-6">
          <div className="relative mb-10 group">
            <div className="absolute inset-0 bg-primary/20 blur-3xl rounded-full animate-pulse" />
            <div className="relative w-32 h-32 bg-card border border-border rounded-[2.5rem] flex items-center justify-center shadow-2xl rotate-3 group-hover:rotate-0 transition-transform duration-500">
              <MessageSquare className="w-12 h-12 text-primary" />
            </div>
          </div>
          <h2 className="text-foreground font-black uppercase tracking-[0.5em] text-sm">Buildesk Command Center</h2>
          <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mt-4">Awaiting lead selection to initialize secure link</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col h-full bg-background transition-colors duration-500">

      {/* CHAT HEADER - with close button like WhatsApp */}
      <div className="h-14 shrink-0 border-b border-border/50 px-3 sm:px-4 flex items-center justify-between bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="flex items-center gap-2 min-w-0 flex-1">
          <Button variant="ghost" size="icon" onClick={handleClose} className="shrink-0 h-9 w-9 rounded-lg hover:bg-muted" title="Close chat">
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <Avatar className="w-9 h-9 shrink-0 border border-primary/20">
            <AvatarFallback className="bg-primary/10 text-primary text-xs font-semibold">
              {displayName.slice(0, 2).toUpperCase()}
            </AvatarFallback>
          </Avatar>
          <div className="min-w-0 flex-1">
            <h3 className="font-semibold text-foreground text-sm truncate">{displayName}</h3>
            <p className="text-[10px] text-muted-foreground truncate flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              {activeContact}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-0.5 shrink-0">
          <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground rounded-lg"><Phone className="w-4 h-4" /></Button>
          <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground rounded-lg"><Video className="w-4 h-4" /></Button>
          <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground hover:text-foreground rounded-lg"><MoreVertical className="w-4 h-4" /></Button>
        </div>
      </div>

      {/* MESSAGES AREA */}
      <div ref={scrollRef} className="flex-1 min-h-0 overflow-y-auto p-4 sm:p-5 space-y-3 bg-background custom-scrollbar">
        {isLoading && messages.length === 0 ? (
          <div className="flex flex-col items-center justify-center pt-20 gap-4 opacity-50">
            <Loader2 className="w-8 h-8 animate-spin text-primary" />
            <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Decrypting History...</span>
          </div>
        ) : (
          messages.map((msg, index) => {
            const prev = index > 0 ? messages[index - 1] : null;
            const dayKey = getDayKey(msg.time);
            const prevDayKey = prev ? getDayKey(prev.time) : null;
            const showDaySeparator = index === 0 || (dayKey !== "unknown" && dayKey !== prevDayKey);
            const dayLabel = showDaySeparator ? formatDayLabel(msg.time) : "";

            return (
              <div key={index} className="space-y-3">
                {showDaySeparator && dayLabel && (
                  <div className="flex items-center justify-center">
                    <div className="px-3 py-1 rounded-full bg-muted/50 border border-border/50 text-[10px] font-semibold text-muted-foreground">
                      {dayLabel}
                    </div>
                  </div>
                )}
                <div className={cn("flex flex-col", msg.is_from_me ? "items-end" : "items-start")}>
                  <div className={cn(
                    "max-w-[85%] sm:max-w-[70%] px-3.5 py-2.5 rounded-2xl text-[13px] leading-relaxed shadow-sm",
                    msg.is_from_me
                      ? "bg-primary text-primary-foreground rounded-br-md"
                      : "bg-muted/60 border border-border/50 text-foreground rounded-bl-md"
                  )}>
                    <p className="whitespace-pre-wrap">{msg.content}</p>
                    <div className="flex items-center gap-1 mt-1.5 justify-end opacity-70 text-[10px] font-medium">
                      {formatLocalTime(msg.time)}
                      {msg.is_from_me && <ShieldCheck className="w-3 h-3 ml-0.5" />}
                    </div>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* INPUT AREA - compact like WhatsApp; extra right padding so HelpBot doesn't cover send */}
      <div className="shrink-0 p-2 sm:p-3 pr-24 border-t border-border/50 bg-card/30">
        <div className="flex items-center gap-2 mb-2">
          <Button variant="ghost" size="sm" onClick={onOpenTemplates} className="h-7 text-xs rounded-lg gap-1.5 text-muted-foreground hover:text-primary">
            <LayoutTemplate className="w-3.5 h-3.5" /> Library
          </Button>
          <Button variant="ghost" size="sm" onClick={() => aiAssistMutation.mutate()} disabled={aiAssistMutation.isPending || messages.length === 0} className="h-7 text-xs rounded-lg gap-1.5 text-muted-foreground hover:text-primary">
            {aiAssistMutation.isPending ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />} AI Assist
          </Button>
        </div>
        {attachment && (
          <div className="flex items-center gap-2 mb-2 px-2 py-1.5 rounded-lg bg-muted/50 border border-border/50">
            {attachment.type.startsWith("image/") ? (
              <FileImage className="w-4 h-4 text-primary shrink-0" />
            ) : attachment.type.startsWith("audio/") ? (
              <Mic className="w-4 h-4 text-primary shrink-0" />
            ) : (
              <FileText className="w-4 h-4 text-primary shrink-0" />
            )}
            <span className="text-xs font-medium truncate flex-1 min-w-0">{attachment.name}</span>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="h-6 w-6 shrink-0 text-muted-foreground hover:text-destructive"
              onClick={() => { setAttachment(null); if (fileInputRef.current) fileInputRef.current.value = ""; }}
            >
              <X className="w-3.5 h-3.5" />
            </Button>
          </div>
        )}
        <div className="flex items-center gap-2">
          <input
            ref={fileInputRef}
            type="file"
            className="hidden"
            accept={fileAccept}
            onChange={(e) => {
              const f = e.target.files?.[0];
              if (f) setAttachment(f);
              e.target.value = "";
            }}
          />
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="h-8 w-8 shrink-0 text-muted-foreground hover:text-foreground rounded-lg"
                title="Attach document, image, or audio"
              >
                <Paperclip className="w-4 h-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent side="top" align="start" className="min-w-[10rem] z-[200]" style={{ zIndex: 9999 }}>
              <DropdownMenuItem
                onClick={() => {
                  setFileAccept(ATTACHMENT_ACCEPT.document);
                  setTimeout(() => fileInputRef.current?.click(), 0);
                }}
                className="gap-2 cursor-pointer"
              >
                <FileText className="w-4 h-4" />
                Document
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  setFileAccept(ATTACHMENT_ACCEPT.image);
                  setTimeout(() => fileInputRef.current?.click(), 0);
                }}
                className="gap-2 cursor-pointer"
              >
                <FileImage className="w-4 h-4" />
                Image
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  setFileAccept(ATTACHMENT_ACCEPT.audio);
                  setTimeout(() => fileInputRef.current?.click(), 0);
                }}
                className="gap-2 cursor-pointer"
              >
                <Mic className="w-4 h-4" />
                Audio
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Input
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey && !isSending) {
                e.preventDefault();
                handleSend();
              }
            }}
            placeholder={attachment ? "Add a caption (optional)" : "Type a message"}
            className="flex-1 h-10 rounded-xl text-sm border-border/50 bg-muted/30 focus-visible:ring-2 focus-visible:ring-primary/30"
          />
          <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0 text-muted-foreground hover:text-foreground rounded-lg"><Smile className="w-4 h-4" /></Button>
          <Button
            size="icon"
            className="shrink-0 h-10 w-10 bg-primary text-primary-foreground hover:opacity-90 rounded-xl"
            onClick={handleSend}
            disabled={isSending || !canSend}
          >
            {isSending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
          </Button>
        </div>
      </div>
    </div>
  );
}